macro(gle_test)
    find_program(GLE "gle" REQUIRED)
    file(STRINGS "gle.out" files)
    foreach(fin ${files})
        string(REPLACE ".gle" ".pdf" fout ${fin})
        execute_process(COMMAND ${GLE} -d pdf -o ${fout} ${fin} RESULT_VARIABLE res ERROR_VARIABLE gle_err)
        # for some reason all gle output goes to stderr
        string(FIND ${gle_err} "error" found_error)
        if((NOT res EQUAL 0) OR (${found_error} GREATER_EQUAL 0))
            file (WRITE "expad-test-gle.log" ${gle_err})
            message(FATAL_ERROR "Error running gle (${fin}) - see 'expad-test-gle.log'")
        else()
            message(STATUS "File ${fin} was successfully processed.") 
        endif()
    endforeach()
endmacro()

macro(gnuplot_test)
    find_program(GNUPLOT "gnuplot" REQUIRED)
    file(STRINGS "gnuplot.out" files)
    foreach(fin ${files}) 
        # we need to call gnuplot in the directory where the scripts are
        string(REPLACE "gnuplot/" "" filename ${fin}) # remove gnuplot/ dir from file name
        execute_process(COMMAND ${GNUPLOT} ${filename} RESULT_VARIABLE res ERROR_FILE "expad-test-gnuplot.log" WORKING_DIRECTORY "gnuplot" OUTPUT_QUIET)
        if(NOT res EQUAL 0)
            message(FATAL_ERROR "Error running gnuplot (${fin}) - see 'expad-test-gnuplot.log'")
        else()
            message(STATUS "File ${fin} was successfully processed.")
        endif()
    endforeach()
endmacro()

macro(python_test)
    find_program(PYTHON "python" REQUIRED)
    file(STRINGS "python.out" files)
    foreach(fin ${files})
        # we need to call python in the directory where the scripts are
        string(REPLACE "python/" "" filename ${fin}) # remove python/ dir from file name
        execute_process(COMMAND ${PYTHON} ${filename} RESULT_VARIABLE res ERROR_FILE "expad-test-python.log" WORKING_DIRECTORY "python" OUTPUT_QUIET)
        if(NOT res EQUAL 0)
            message(FATAL_ERROR "Error running python (${fin}) - see 'expad-test-python.log'")
        else()
            message(STATUS "File ${fin} was successfully processed.")
        endif()
    endforeach()
endmacro()

if(${TEST} STREQUAL "GLE")
    gle_test()
elseif(${TEST} STREQUAL "GNUPLOT")
    gnuplot_test()
elseif(${TEST} STREQUAL "PYTHON")
    python_test()
else()
    message(FATAL_ERROR "Unknown test : ${TEST}")
endif()
